### ISSUE TITLE
Generated sample library fails on ESP chips

### ISSUE THREAD

**Issue by robonxt** [Embedded-Helper/EmbeddedHelperBetaTest#5]
Sample library was successfully compiled and created. However when trying to upload to a ESP-based platform the library `sketch_jan28a` (as I called it) fails to compile.

- shortened error logs:

  Arduino: 1.8.13 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"
  
  WARNING: library `sketch_jan28a` claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).
  
  Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by jsmith2021Brandeis** [comment]
Hello robonxt, thank you for submitting this issue

I fixed that error in the [New release](https://github.com/Embedded-Helper/EmbeddedHelperBetaTest/releases/tag/1.0.4), the tool used to assume that the avr architecture would be used, now it leaves the Architecture field in library.properties blank

Since you are using an ESP8266 board, I would encourage you to check out the new Supported Boards feature in [the release](https://github.com/Embedded-Helper/EmbeddedHelperBetaTest/releases/tag/1.0.4), See Special Features [in README](https://github.com/jsmith2021Brandeis/EmbeddedHelperBetaTest/). This feature will allow you to only compile the library when a supported board is being used, which is helpful when new users try to use your library
